name = "fifa-world-cup-2026"
main = "app/index.tsx"
compatibility_date = "2025-04-01"

assets = { directory = "./public", binding = "ASSETS" }

# For local dev, wrangler dev auto-creates local D1
[[d1_databases]]
binding = "DB"
database_name = "fifa-db"
database_id = "9c1e7661-6349-4037-bce1-16a8319c67b1"

# For local dev with KV:
# [[kv_namespaces]]
# binding = "KV"
# id = "local-dev"
