name = "fifa-world-cup-2026"
main = "app/index.tsx"
compatibility_date = "2025-04-01"

assets = { directory = "./public", binding = "ASSETS" }

# For local dev, wrangler dev auto-creates local D1
[[d1_databases]]
binding = "DB"
database_name = "fifa-db"
database_id = "e4a0cd81-fa4d-4339-9150-84a822a60661"

# For local dev with KV:
# [[kv_namespaces]]
# binding = "KV"
# id = "local-dev"
